apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-tls
  namespace: default
spec:
  secretName: nginx-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - nginx.srv-k3s.server.io